export const mockEpisodes = [
  {
    slug: 'building-internal-developer-platforms',
    title: 'Building Internal Developer Platforms That Teams Actually Want to Use',
    description: 'Sarah Chen from Spotify joins us to discuss how they built Backstage and the lessons learned about creating developer experiences that stick.',
    guest: {
      name: 'Sarah Chen',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=800&fit=crop&crop=face',
      title: 'Staff Engineer',
      company: 'Spotify',
    },
    topics: ['DevOps', 'Platform Engineering'],
    duration: '58 min',
    date: 'Nov 20, 2024',
    plays: 2400,
    episodeNumber: 47,
  },
  {
    slug: 'future-of-kubernetes',
    title: 'The Future of Kubernetes: What\'s Next After Containers',
    description: 'Kelsey Hightower explores the evolution of container orchestration and what comes next.',
    guest: {
      name: 'Kelsey Hightower',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop&crop=face',
      title: 'Developer Advocate',
      company: 'Google Cloud',
    },
    topics: ['Cloud'],
    duration: '45 min',
    date: 'Nov 15, 2024',
    plays: 1890,
  },
  {
    slug: 'engineering-management-remote-first',
    title: 'Engineering Management in a Remote-First World',
    description: 'Camille Fournier shares insights on leading engineering teams in distributed environments.',
    guest: {
      name: 'Camille Fournier',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&h=800&fit=crop&crop=face',
      title: 'Author & Consultant',
      company: 'The Manager\'s Path',
    },
    topics: ['Leadership'],
    duration: '52 min',
    date: 'Nov 10, 2024',
    plays: 1720,
  },
  {
    slug: 'incident-management-burnout',
    title: 'Incident Management That Doesn\'t Burn Out Your Team',
    description: 'Nora Jones from Jeli.io discusses sustainable incident response practices.',
    guest: {
      name: 'Nora Jones',
      photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=800&fit=crop&crop=face',
      title: 'CEO',
      company: 'Jeli.io',
    },
    topics: ['SRE'],
    duration: '48 min',
    date: 'Nov 5, 2024',
    plays: 1650,
  },
];

export const mockArticles = [
  {
    slug: '5-metrics-platform-teams',
    title: '5 Metrics That Actually Matter for Platform Teams',
    description: 'Stop tracking vanity metrics. Here\'s what successful platform engineering teams measure to prove value and drive adoption.',
    topic: 'DevOps',
    readTime: '5 min read',
    date: 'Nov 18, 2024',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=300&fit=crop',
    author: {
      name: 'Sarah Chen',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face',
      title: 'Staff Engineer at Spotify',
    },
  },
  {
    slug: 'why-engineers-hate-ci-pipeline',
    title: 'Why Your Engineers Hate Your CI Pipeline',
    description: 'The hidden costs of slow builds and how to fix them without a complete rewrite.',
    topic: 'Culture',
    readTime: '8 min read',
    date: 'Nov 12, 2024',
    image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&h=300&fit=crop',
  },
];

export const mockGuests = [
  {
    slug: 'sarah-chen',
    name: 'Sarah Chen',
    title: 'Staff Engineer',
    company: 'Spotify',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&h=500&fit=crop&crop=face',
    bio: 'Sarah is a Staff Engineer at Spotify where she leads the Backstage core team. She\'s passionate about developer experience and has spent the last decade building platforms that engineers actually want to use. Previously at Google and Netflix.',
    episodeCount: 3,
    topics: ['DevOps', 'Platform Engineering', 'Developer Experience'],
    social: {
      twitter: '@sarahchen',
      linkedin: 'linkedin.com/in/sarahchen',
      website: 'sarahchen.dev',
    },
  },
  {
    slug: 'kelsey-hightower',
    name: 'Kelsey Hightower',
    title: 'Developer Advocate',
    company: 'Google Cloud',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop&crop=face',
    bio: 'Kelsey is a legendary figure in the Kubernetes and cloud native community, known for making complex systems accessible.',
    episodeCount: 2,
    topics: ['Cloud', 'Kubernetes', 'DevOps'],
    social: {
      twitter: '@kelseyhightower',
      linkedin: 'linkedin.com/in/kelseyhightower',
    },
  },
  {
    slug: 'camille-fournier',
    name: 'Camille Fournier',
    title: 'Author & Consultant',
    company: 'The Manager\'s Path',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&h=500&fit=crop&crop=face',
    bio: 'Author of "The Manager\'s Path" and expert on engineering leadership.',
    episodeCount: 2,
    topics: ['Leadership', 'Management'],
    social: {
      twitter: '@skamille',
      linkedin: 'linkedin.com/in/camillefournier',
    },
  },
  {
    slug: 'nora-jones',
    name: 'Nora Jones',
    title: 'CEO',
    company: 'Jeli.io',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&h=500&fit=crop&crop=face',
    bio: 'CEO of Jeli.io, focused on improving incident management and learning from failures.',
    episodeCount: 1,
    topics: ['SRE', 'DevOps', 'Incident Management'],
    social: {
      twitter: '@nora_js',
      linkedin: 'linkedin.com/in/norajones',
    },
  },
];

export const mockTopics = [
  { slug: 'devops', name: 'DevOps', icon: 'refresh', count: { episodes: 12, articles: 8 } },
  { slug: 'cloud', name: 'Cloud', icon: 'cloud', count: { episodes: 8, articles: 5 } },
  { slug: 'leadership', name: 'Leadership', icon: 'users', count: { episodes: 10, articles: 6 } },
  { slug: 'kubernetes', name: 'Kubernetes', icon: 'server', count: { episodes: 7, articles: 4 } },
  { slug: 'platform-engineering', name: 'Platform Engineering', icon: 'layers', count: { episodes: 9, articles: 7 } },
  { slug: 'sre', name: 'SRE', icon: 'shield', count: { episodes: 6, articles: 5 } },
  { slug: 'culture', name: 'Culture', icon: 'heart', count: { episodes: 5, articles: 8 } },
  { slug: 'architecture', name: 'Architecture', icon: 'box', count: { episodes: 8, articles: 6 } },
  { slug: 'cicd', name: 'CI/CD', icon: 'git-branch', count: { episodes: 7, articles: 9 } },
  { slug: 'observability', name: 'Observability', icon: 'eye', count: { episodes: 4, articles: 3 } },
];
