export const mockEpisodes = [
  {
    slug: 'building-internal-developer-platforms',
    title: 'Building Internal Developer Platforms That Teams Actually Want to Use',
    description: 'Sarah Chen from Spotify joins us to discuss how they built Backstage and the lessons learned about creating developer experiences that stick.',
    guest: {
      name: 'Sarah Chen',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=800&fit=crop&crop=face',
      title: 'Staff Engineer',
      company: 'Spotify',
    },
    topics: ['DevOps', 'Platform Engineering'],
    duration: '58 min',
    date: 'Nov 20, 2024',
    plays: 2400,
    episodeNumber: 47,
  },
  {
    slug: 'future-of-kubernetes',
    title: 'The Future of Kubernetes: What\'s Next After Containers',
    description: 'Kelsey Hightower explores the evolution of container orchestration and what comes next.',
    guest: {
      name: 'Kelsey Hightower',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop&crop=face',
      title: 'Developer Advocate',
      company: 'Google Cloud',
    },
    topics: ['Cloud'],
    duration: '45 min',
    date: 'Nov 15, 2024',
    plays: 1890,
  },
  {
    slug: 'engineering-management-remote-first',
    title: 'Engineering Management in a Remote-First World',
    description: 'Camille Fournier shares insights on leading engineering teams in distributed environments.',
    guest: {
      name: 'Camille Fournier',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&h=800&fit=crop&crop=face',
      title: 'Author & Consultant',
      company: 'The Manager\'s Path',
    },
    topics: ['Leadership'],
    duration: '52 min',
    date: 'Nov 10, 2024',
    plays: 1720,
  },
  {
    slug: 'incident-management-burnout',
    title: 'Incident Management That Doesn\'t Burn Out Your Team',
    description: 'Nora Jones from Jeli.io discusses sustainable incident response practices.',
    guest: {
      name: 'Nora Jones',
      photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=800&fit=crop&crop=face',
      title: 'CEO',
      company: 'Jeli.io',
    },
    topics: ['SRE'],
    duration: '48 min',
    date: 'Nov 5, 2024',
    plays: 1650,
  },
];

export const mockArticles = [
  {
    slug: 'wesco-data-center-boom-q3-2025',
    title: 'How Wesco Is Riding the Data Center Boom to Record Sales',
    description: 'Wesco\'s Q3 2025 results show 60% YoY data center growth driving $6.2B in quarterly revenue. What distributors can learn from their strategy.',
    topic: 'Distribution',
    readTime: '6 min read',
    date: 'Nov 25, 2024',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=300&fit=crop',
    author: {
      name: 'Marcus Thompson',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
      title: 'Industry Analyst',
    },
  },
  {
    slug: 'grainger-distribution-automation',
    title: 'Inside Grainger\'s $500M Bet on Automated Distribution',
    description: 'W.W. Grainger\'s new Oregon distribution center promises next-day delivery to 99% of the US market. Here\'s how automation is reshaping industrial distribution.',
    topic: 'Supply Chain',
    readTime: '7 min read',
    date: 'Nov 22, 2024',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=300&fit=crop',
    author: {
      name: 'Jennifer Walsh',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face',
      title: 'Supply Chain Editor',
    },
  },
  {
    slug: 'b2b-ecommerce-80-percent-digital',
    title: '80% of B2B Sales Will Be Digital by End of 2025',
    description: 'The B2B ecommerce market is racing toward $62 trillion by 2030. Are industrial distributors ready for the shift?',
    topic: 'B2B Commerce',
    readTime: '8 min read',
    date: 'Nov 20, 2024',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=300&fit=crop',
    author: {
      name: 'David Park',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
      title: 'Digital Commerce Strategist',
    },
  },
  {
    slug: 'industrial-distribution-ai-personalization',
    title: 'How AI Is Cutting Procurement Costs by 15% in Industrial Distribution',
    description: 'From dynamic pricing to predictive inventory, AI and generative AI are becoming top investment priorities for B2B distributors in 2025.',
    topic: 'Digital Transformation',
    readTime: '5 min read',
    date: 'Nov 18, 2024',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&h=300&fit=crop',
    author: {
      name: 'Sarah Chen',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face',
      title: 'Staff Engineer at Spotify',
    },
  },
  {
    slug: 'marketplace-platforms-dominate-b2b',
    title: 'Why Marketplace Platforms Now Control 65% of B2B Transactions',
    description: 'B2B marketplaces are growing at 18% annually. Here\'s what traditional distributors need to know to compete.',
    topic: 'B2B Commerce',
    readTime: '6 min read',
    date: 'Nov 15, 2024',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=600&h=300&fit=crop',
  },
  {
    slug: 'wesco-sustainability-report-2025',
    title: 'Wesco\'s 2025 Sustainability Push: 30% Emissions Cut by 2030',
    description: 'Inside Wesco\'s ESG strategy including greenhouse gas reduction targets and 425,000 hours of safety training goals.',
    topic: 'Supply Chain',
    readTime: '4 min read',
    date: 'Nov 10, 2024',
    image: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=600&h=300&fit=crop',
  },
];

export const mockGuests = [
  {
    slug: 'john-engel',
    name: 'John Engel',
    title: 'Chairman & CEO',
    company: 'Wesco International',
    photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&h=500&fit=crop&crop=face',
    bio: 'John Engel has led Wesco International since 2009, transforming it into a Fortune 500 leader in B2B distribution. Under his leadership, Wesco completed the landmark Anixter acquisition and has driven record growth in data center and communications solutions.',
    episodeCount: 3,
    topics: ['Distribution', 'Leadership', 'Digital Transformation'],
    social: {
      linkedin: 'linkedin.com/in/johnengel',
    },
  },
  {
    slug: 'dt-hightower',
    name: 'D.G. Macpherson',
    title: 'Chairman & CEO',
    company: 'W.W. Grainger',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&h=500&fit=crop&crop=face',
    bio: 'D.G. Macpherson has been leading Grainger\'s transformation into a digital-first industrial distributor. His focus on supply chain automation and next-day delivery has positioned Grainger as a leader in MRO distribution.',
    episodeCount: 2,
    topics: ['Supply Chain', 'B2B Commerce', 'Automation'],
    social: {
      linkedin: 'linkedin.com/in/dgmacpherson',
    },
  },
  {
    slug: 'barry-greenhouse',
    name: 'Barry Greenhouse',
    title: 'SVP, Global Supply Chain',
    company: 'W.W. Grainger',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&h=500&fit=crop&crop=face',
    bio: 'Barry Greenhouse oversees Grainger\'s entire distribution network including 35 DCs worldwide. He\'s the architect behind their 99% next-day delivery promise and the new 500,000 sq ft Oregon distribution center.',
    episodeCount: 2,
    topics: ['Logistics', 'Supply Chain', 'Automation'],
    social: {
      linkedin: 'linkedin.com/in/barrygreenhouse',
    },
  },
  {
    slug: 'jennifer-chen',
    name: 'Jennifer Chen',
    title: 'VP Digital Commerce',
    company: 'HD Supply',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&h=500&fit=crop&crop=face',
    bio: 'Jennifer leads digital transformation initiatives at HD Supply, focusing on B2B ecommerce platforms and customer experience. Previously at Amazon Business and Alibaba.',
    episodeCount: 3,
    topics: ['B2B Commerce', 'Digital Transformation', 'AI & Analytics'],
    social: {
      twitter: '@jenniferchen',
      linkedin: 'linkedin.com/in/jenniferchen',
    },
  },
  {
    slug: 'marcus-thompson',
    name: 'Marcus Thompson',
    title: 'Industry Analyst',
    company: 'Distribution Strategy Group',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop&crop=face',
    bio: 'Marcus is a leading analyst covering industrial distribution and B2B commerce. His research on digital transformation in wholesale distribution is widely cited across the industry.',
    episodeCount: 4,
    topics: ['Distribution', 'B2B Commerce', 'Industrial'],
    social: {
      twitter: '@mthompson_dist',
      linkedin: 'linkedin.com/in/marcusthompson',
      website: 'distributionstrategy.com',
    },
  },
  {
    slug: 'lisa-anderson',
    name: 'Lisa Anderson',
    title: 'President',
    company: 'LMA Consulting Group',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&h=500&fit=crop&crop=face',
    bio: 'Lisa is a supply chain and manufacturing expert helping distributors navigate digital transformation. Named a Top 40 B2B Tech Influencer, she advises Fortune 500 companies on operational excellence.',
    episodeCount: 2,
    topics: ['Supply Chain', 'Leadership', 'Sustainability'],
    social: {
      twitter: '@lisaanderson',
      linkedin: 'linkedin.com/in/lisaanderson',
      website: 'lma-consultinggroup.com',
    },
  },
];

export const mockTopics = [
  { slug: 'distribution', name: 'Distribution', icon: 'truck', count: { episodes: 15, articles: 12 } },
  { slug: 'supply-chain', name: 'Supply Chain', icon: 'link', count: { episodes: 12, articles: 10 } },
  { slug: 'b2b-commerce', name: 'B2B Commerce', icon: 'shopping-cart', count: { episodes: 10, articles: 8 } },
  { slug: 'digital-transformation', name: 'Digital Transformation', icon: 'refresh', count: { episodes: 14, articles: 11 } },
  { slug: 'logistics', name: 'Logistics', icon: 'package', count: { episodes: 9, articles: 7 } },
  { slug: 'industrial', name: 'Industrial', icon: 'settings', count: { episodes: 8, articles: 6 } },
  { slug: 'automation', name: 'Automation', icon: 'cpu', count: { episodes: 11, articles: 9 } },
  { slug: 'sustainability', name: 'Sustainability', icon: 'leaf', count: { episodes: 6, articles: 5 } },
  { slug: 'leadership', name: 'Leadership', icon: 'users', count: { episodes: 10, articles: 6 } },
  { slug: 'ai-analytics', name: 'AI & Analytics', icon: 'bar-chart', count: { episodes: 7, articles: 8 } },
];
